### ISSUE TITLE
increase version code android not working

### ISSUE THREAD

**Issue by meosieudang** [codemagic-ci-cd/react-native-demo-project#2]
![Screen Shot 2021-04-09 at 5 05 14 PM](https://user-images.githubusercontent.com/45912335/114164678-c61d2200-9955-11eb-82b6-5a9f68936176.png)
Here is code increase version code android:
 export NEW_BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME") + 1))

app/build.gradle
versionCode Integer.valueOf(System.getenv("NEW_BUILD_NUMBER"))

**Comment by nevercode-kevin** [comment]
Please contact Codemagic support if you are having issues with your build instead of commenting on this repository. If you have billing enabled use the chat widget at the bottom right of the screen to talk directly with support. If you are on a free plan then you can ask questions in the Slack community by clicking on the question mark icon in the Codemagic web app and clicking on 'Slack community'. If your build is failing that include the 'build link' which is the URL from the browser address bar where you see the build logs.
