### ISSUE TITLE
build fail with RN fast image

### ISSUE THREAD

**Issue by meosieudang** [codemagic-ci-cd/react-native-demo-project#3]
![Screen Shot 2021-04-12 at 11 10 01 AM](https://user-images.githubusercontent.com/45912335/114339541-b123d700-9b7f-11eb-823d-6dd19a049554.png)

**Comment by nevercode-kevin** [comment]
Please contact Codemagic support if you are having issues with your build instead of commenting on this repository. If you have billing enabled use the chat widget at the bottom right of the screen to talk directly with support. If you are on a free plan then you can ask questions in the Slack community by clicking on the question mark icon in the Codemagic web app and clicking on 'Slack community'. If your build is failing that include the 'build link' which is the URL from the browser address bar where you see the build logs.
